# -*- coding: utf-8 -*-
"""Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrsR9q-5Q8xQqKbSoINVQ3HaQnOH5Ku_

Creating numpy arrays
"""

import numpy as np
a=np.array([1,2,3,4])
a

a=np.arange(12).reshape((3,4))
b=np.arange(12).reshape((4,3))
a

a=np.ones((3,4))
a

a=np.zeros((4,3))
a

a1=np.random.random((3,4))
a1

a2=np.random.randint(-10,10,20)
a2

a=np.linspace(-20,10,10)
a

a=np.identity(4)
a

"""Attributes

"""

a=np.arange(12).reshape((3,4))
a

a.shape

a.dtype

a.itemsize

a.size

a=a.astype(np.int32)

a.dtype

"""functions

"""

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

np.sin(a)

a2=np.random.random((2,3))
a2=a2*100
a2

np.round(a2)

np.floor(a2)

np.ceil(a2)

np.max(a2,axis=0)

np.min(a2,axis=1)



"""slicing"""

a1=np.arange(10)
a2=np.arange(12).reshape((3,4))
a3=np.arange(8).reshape((2,2,2))
print(a1)
print(a2)
print(a3)

a1[1:4]

a2[::2,1::2]

a3[0]

a3[:,0,:]

"""Advanced Indexing"""

a=np.arange(12).reshape(4,3)
a

a[[0,2,3]]

a[:,[0,2]]

"""Boolean Indexing"""

a=np.random.randint(1,100,24).reshape(6,4)
a

a[a>50]

a[a%2==0]

a[~a%7==0]

a[(a>50)&(a%7==0)]

"""Broadcasting"""

a=np.arange(12).reshape(3,4)
b=np.arange(4)
print(a)
print(b)

print(a+b)